language: php
php:
  - '7.0'

before_script:
  - composer self-update
  - composer install
  - ./vendor/bin/phpcs --config-set installed_paths /home/travis/build/Khristophor/wp-plugin-scaffold/vendor/wp-coding-standards/wpcs/

script:
  - ./vendor/bin/phpcs -p . --standard=WordPress-Extra
